### ISSUE TITLE
Vertical & rotation issues

### ISSUE THREAD

**Issue by mtedesco** [doukasd/iOS-Components#1]
I love this control, however I need to implement it vertically for an educational app I'm writing.

I believe the simplest solution would be to rotate your control, however, when I rotate at 90-degree increments, the max slider gets stuck in the max position and becomes unmovable.   

Can you suggest a solution?  Again, very grateful you shared this.  Just need some pointers to get this to work vertically.  

```
//DoubleSlider setup
DoubleSlider *slider = [DoubleSlider doubleSlider];
[slider addTarget:self action:@selector(valueChangedForDoubleSlider:) forControlEvents:UIControlEventValueChanged];
slider.center = self.view.center;
slider.minSelectedValue = 20;
slider.maxSelectedValue = 40;
slider.transform = CGAffineTransformRotate(slider.transform, 90.0/180*M_PI);    //THIS WORKS IF 45.0, but not at 90 or 270
[self.view addSubview:slider];
```

Best,

Mike

**Comment by doukasd** [comment]
Hi Mike,

I'm really glad you find this useful.
About having it vertical... I'm afraid the only solution I can think of would be to duplicate the control and make a new vertical implementation, since the control now specifically works with touch.x, handle.x, slider.width etc. All these should be changed to "y" and "height" but I think it should be a fairly easy task.

You question is quite interesting really. I'm wondering if Apple's controls work if they are rotated. I'm thinking they probably do and in that case there is some bad coding done in that control from me :) If you have more ideas or information on this please let me know, I should be able to look into it the coming week.

Cheers
Dimitris

**Comment by mtedesco** [comment]
Dimitris, thank you so much for the speedy reply.   

I believe the solution might be much easier than you mention:  try my code block in your sample code app as follows, using 45 degrees as the rotation value:

slider.transform = CGAffineTransformRotate(slider.transform, 45.0/180*M_PI);   

Your control works fine when rotated to 45 degrees.  Interesting!   

Maybe it is just a matter of testing & handling a few boundary/edge cases differently?   If you just paste in that one line and test you'll see what I'm saying.  Then, experiment with different rotations.  

Anyways I'm really glad you shared your project.  Perhaps we can continue to work together to figure this out and find a way to avoid a rewrite.

**Comment by doukasd** [comment]
That's interesting. The behaviour is quite buggy when the angle is steep, which leads me to think it's an issue in the drawing on the component. Seems like something easy to fix, let's see if it is..
I appreciate your contribution :)

**Comment by doukasd** [comment]
Hi mtedesco,

I fixed the issue and updated the code. Please have a look, it should be fine as a vertical slider too!
Thanks for reporting.

**Comment by mtedesco** [comment]
Thanks!  Nice job.  It works well in the simulator.   I'm going to start working on testing/styling it for the project I'm doing.  The goal will be to incorporate it vertically and to show three different color bands.  I'll let you know how it goes.   Thank you again for helping support the rotation requirement.   

Best, 

Mike
